name: Java CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run tests
        run: mvn -B test

      - name: Check code format
        run: mvn -B spotless:check

      - name: Format code (if needed)
        if: failure() && steps.check-format.outcome == 'failure'
        run: |
          mvn -B spotless:apply
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "style: auto-format code" || echo "No formatting changes"
          git push